server:
  port: 9400

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cdb-0iezsypz.sql.tencentcdb.com:59218/store_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Root12345

    # 服务注册
  cloud:
    nacos:
      discovery:
        server-addr:  47.97.69.141:8848
        namespace: c8bceb9e-4b19-446e-a836-8bcb843871be


# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: pers.store.market.ware.entity
  global-config:
    db-config:
      id-type: auto   #id策略自增长,可以使用zookeeper生成主键ID
    #原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'