spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
      routes:
        - id: store-product-route
          uri: lb://store-product  # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          order: 1   # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/product/** #当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 #转发之前去掉1层路径