server:
  port: 9500

# 服务注册
spring:
  cloud:
    nacos:
      discovery:
        server-addr:  47.97.69.141:8848
        namespace: c8bceb9e-4b19-446e-a836-8bcb843871be

  thymeleaf:
    cache: false

es:
  host: 172.16.97.3
  port: 9200
  scheme: http

logging:
   level:
     pers.store.market.search: info
