server:
  port: 10000

spring:
  cloud:
    alicloud:
      access-key: LTAI4G2TkFoXWsbUAJc79eDJ
      secret-key: 5eee6MsTUUkRObkHZxLhOT8HEz5iPv
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: 2021-test
    nacos:
      discovery:
        server-addr: 47.97.69.141:8848
        namespace: c8bceb9e-4b19-446e-a836-8bcb843871be